# Generated by Django 3.2.9 on 2022-02-02 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=500)),
                ('entity', models.CharField(default='', max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('id', models.IntegerField(default=1)),
                ('content', models.TextField()),
                ('text', models.TextField(default='')),
                ('key', models.TextField(default='')),
                ('measures', models.TextField(default='')),
                ('asavoir', models.TextField(default='')),
                ('forewords', models.TextField(default='')),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='ExternalPage',
            fields=[
                ('id', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('content', models.TextField(default='')),
                ('entity', models.CharField(default='', max_length=500)),
                ('doctype', models.CharField(default='', max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('html', models.TextField(default='')),
                ('markdown', models.TextField(default='')),
                ('url', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('number', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=500)),
                ('entity', models.CharField(default='', max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('id', models.IntegerField(default=1)),
                ('content', models.TextField()),
                ('main_title', models.CharField(default='', max_length=500)),
                ('text', models.TextField(default='')),
                ('forewords', models.TextField(default='')),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='UrlData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=15)),
            ],
            options={
                'ordering': ('slug',),
            },
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.TextField(default='')),
                ('key', models.BooleanField(default=False)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.article')),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('number', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=500)),
                ('entity', models.CharField(default='', max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('id', models.IntegerField(default=1)),
                ('content', models.TextField()),
                ('main_title', models.CharField(default='', max_length=500)),
                ('sub_title', models.CharField(default='', max_length=500)),
                ('text', models.TextField(default='')),
                ('part', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='core.part')),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.AddField(
            model_name='article',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.chapter'),
        ),
    ]
