# Generated by Django 3.2.5 on 2021-08-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='chapter',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
