# Generated by Django 3.2.9 on 2022-01-15 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chapter_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='asavoir',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='forewords',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='key',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='measures',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='part',
            name='forewords',
            field=models.TextField(default=''),
        ),
    ]
