# Generated by Django 3.2.5 on 2021-10-10 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210825_1637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urldata',
            options={'ordering': ('slug',)},
        ),
    ]
