# Generated by Django 3.2.5 on 2021-07-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210128_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='entity',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='chapter',
            name='entity',
            field=models.CharField(default='', max_length=500),
        ),
    ]
