# Generated by Django 3.2.5 on 2021-07-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210713_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='main_title',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='chapter',
            name='sub_title',
            field=models.CharField(default='', max_length=500),
        ),
    ]
