# Generated by Django 3.2.9 on 2022-02-02 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_externalpage_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalpage',
            name='markdown',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='externalpage',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='externalpage',
            name='html',
            field=models.TextField(default=''),
        ),
    ]
