# Generated by Django 3.2.9 on 2022-02-02 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20220202_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalpage',
            name='doctype',
            field=models.CharField(default='', max_length=100),
        ),
    ]
